# Generated by Django 5.0.6 on 2026-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "hash",
                    models.CharField(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
