# Generated by Django 6.0.2 on 2026-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="url",
            field=models.URLField(editable=False),
        ),
    ]
